import { AnalyticsEmptyBlock } from "@/components/analytics/analytics-empty-block";
import {
  formatAnalyticsEnum,
  safeMetricNumber
} from "@/components/analytics/analytics-formatters";
import type { HeroMasteryNote } from "@/lib/analytics-data";
import { classNames } from "@/lib/utils";

export function HeroMasteryNotes({ notes }: Readonly<{ notes: HeroMasteryNote[] }>) {
  if (notes.length === 0) {
    return (
      <AnalyticsEmptyBlock
        title="No deterministic notes returned."
        detail="Hero mastery notes are generated by backend rules when enough signal exists."
      />
    );
  }

  return (
    <section className="analytics-mastery-card">
      <div className="analytics-mastery-card-header">
        <div>
          <span className="ops-label">Deterministic notes</span>
          <strong>How to Read This Hero</strong>
        </div>
      </div>
      <div className="analytics-mastery-note-grid">
        {notes.map((note, index) => (
          <article
            className={classNames(
              "analytics-mastery-note-card",
              `is-${note.severity.toLowerCase()}`
            )}
            key={`${note.category}-${note.metricName ?? "note"}-${index}`}
          >
            <div>
              <span className="ops-badge">{formatAnalyticsEnum(note.category)}</span>
              <span className={classNames("analytics-note-severity", `is-${note.severity.toLowerCase()}`)}>
                {formatAnalyticsEnum(note.severity)}
              </span>
            </div>
            <strong>{note.metricName ? formatAnalyticsEnum(note.metricName) : "Hero mastery"}</strong>
            <p>{note.message}</p>
            {note.currentValue !== null || note.baselineValue !== null ? (
              <dl>
                {note.currentValue !== null ? (
                  <>
                    <dt>Current</dt>
                    <dd>{safeMetricNumber(note.currentValue, 2)}</dd>
                  </>
                ) : null}
                {note.baselineValue !== null ? (
                  <>
                    <dt>Baseline</dt>
                    <dd>{safeMetricNumber(note.baselineValue, 2)}</dd>
                  </>
                ) : null}
              </dl>
            ) : null}
          </article>
        ))}
      </div>
    </section>
  );
}
