import { AnalyticsEmptyBlock } from "@/components/analytics/analytics-empty-block";
import {
  formatAnalyticsEnum,
  safeMetricNumber
} from "@/components/analytics/analytics-formatters";
import type {
  HeroMasteryNote,
  HeroMasteryNoteCategory
} from "@/lib/analytics-data";
import { classNames } from "@/lib/utils";

const NOTE_CATEGORY_ORDER: HeroMasteryNoteCategory[] = [
  "ECONOMY",
  "FIGHTING",
  "OBJECTIVE",
  "SURVIVABILITY",
  "CONTEXT",
  "SAMPLE_SIZE"
];

export function HeroMasteryNotes({ notes }: Readonly<{ notes: HeroMasteryNote[] }>) {
  if (notes.length === 0) {
    return (
      <AnalyticsEmptyBlock
        title="No deterministic notes returned."
        detail="Hero mastery notes are generated by backend rules when enough signal exists."
      />
    );
  }

  return (
    <section className="analytics-mastery-card">
      <div className="analytics-mastery-card-header">
        <div>
          <span className="ops-label">Deterministic notes</span>
          <strong>How to Read This Hero</strong>
        </div>
      </div>
      {shouldGroupNotes(notes) ? <GroupedNotes notes={notes} /> : <SimpleNotes notes={notes} />}
    </section>
  );
}

function SimpleNotes({ notes }: Readonly<{ notes: HeroMasteryNote[] }>) {
  return (
    <div className="analytics-mastery-note-grid">
      {notes.map((note, index) => renderNoteCard(note, index))}
    </div>
  );
}

function GroupedNotes({ notes }: Readonly<{ notes: HeroMasteryNote[] }>) {
  return (
    <div className="analytics-mastery-note-sections">
      {NOTE_CATEGORY_ORDER.map((category) => {
        const categoryNotes = notes.filter((note) => note.category === category);

        if (categoryNotes.length === 0) {
          return null;
        }

        return (
          <section className="analytics-mastery-note-section" key={category}>
            <div className="analytics-mastery-note-section-header">
              <span className="ops-label">{formatAnalyticsEnum(category)}</span>
              <p>{categoryNotes.length} backend rule {categoryNotes.length === 1 ? "note" : "notes"}</p>
            </div>
            <div className="analytics-mastery-note-grid">
              {categoryNotes.map((note, index) => renderNoteCard(note, index))}
            </div>
          </section>
        );
      })}
    </div>
  );
}

function shouldGroupNotes(notes: HeroMasteryNote[]) {
  return notes.length >= 3 && new Set(notes.map((note) => note.category)).size > 1;
}

function renderNoteCard(note: HeroMasteryNote, index: number) {
  return (
    <article
      className={classNames(
        "analytics-mastery-note-card",
        `is-${note.severity.toLowerCase()}`
      )}
      key={`${note.category}-${note.metricName ?? "note"}-${index}`}
    >
      <div>
        <span className="ops-badge">{formatAnalyticsEnum(note.category)}</span>
        <span className={classNames("analytics-note-severity", `is-${note.severity.toLowerCase()}`)}>
          {formatAnalyticsEnum(note.severity)}
        </span>
      </div>
      <strong>{note.metricName ? formatAnalyticsEnum(note.metricName) : "Hero mastery"}</strong>
      <p>{note.message}</p>
      {note.currentValue !== null || note.baselineValue !== null ? (
        <dl>
          {note.currentValue !== null ? (
            <>
              <dt>Current</dt>
              <dd>{safeMetricNumber(note.currentValue, 2)}</dd>
            </>
          ) : null}
          {note.baselineValue !== null ? (
            <>
              <dt>Baseline</dt>
              <dd>{safeMetricNumber(note.baselineValue, 2)}</dd>
            </>
          ) : null}
        </dl>
      ) : null}
    </article>
  );
}
